name: wp-dev-helpers
recipe: wordpress
config:
  webroot: webroot

tooling:
  setup:
    service: appserver
    cmd:
      - /app/.lando/install-wordpress.sh
      - ln -s ../../src /app/webroot/wp-content/mu-plugins
      - /app/.lando/setup-test-posts.sh